# Generated by Django 4.2.21 on 2025-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
