# Generated by Django 4.2.21 on 2025-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], default='user', max_length=10),
        ),
    ]
