# Generated by Django 4.2.21 on 2025-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user_is_admin_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10),
        ),
    ]
