# Generated by Django 4.2.21 on 2025-06-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_rechargerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
