# Generated by Django 4.2.21 on 2025-06-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_rechargerecord_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
